spring:
  application:
    name: order-demo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/order_demo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.orderdemo: INFO
  file:
    name: logs/order-demo.log